### ISSUE TITLE
marginalPrediction calls 'predict' changes order of data columns before calling predict

### ISSUE THREAD

**Issue by mb706** [zmjones/mmpf#2]
See mlr-org/mlr#2439. `makeDesign` changes the order of data columns:
```r
> colnames(iris)
[1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"
> colnames(mmpf::makeDesign(iris, "Petal.Width", dim(iris)))
[1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Species"      "Petal.Width"
```
which is fine by itself. However, when it is used in `marginalPrediction`, the `predict` function is then called with this reordered data, which breaks in some cases where `predict` expects the order of columns to match the order during model fitting. A fix for this would be a `design = design[colnames(vars)data)]`, or a change in `makeDesign` that preserves column order.

**Comment by zmjones** [comment]
i'll see about fixing it here as that probably will occur outside of mlr as well

**Comment by zmjones** [comment]
being preserved now. i'll push it up to cran so it stops irritating!
